# Generated by Django 4.2.1 on 2023-06-04 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(unique=True)),
                ('phone_number', models.CharField(max_length=50)),
                ('adress', models.CharField(max_length=100)),
            ],
        ),
    ]
