# Generated by Django 4.2.1 on 2023-06-08 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_alter_film_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='available_in_countries',
            field=models.ManyToManyField(related_name='films_available', to='films.country'),
        ),
        migrations.AlterField(
            model_name='film',
            name='category',
            field=models.ManyToManyField(related_name='films', to='films.category'),
        ),
        migrations.AlterField(
            model_name='film',
            name='created_in_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='films_created', to='films.country'),
        ),
        migrations.AlterField(
            model_name='film',
            name='director',
            field=models.ManyToManyField(related_name='films', to='films.director'),
        ),
    ]
